version: '3' 
services: 
   mssql: 
     image: 'mcr.microsoft.com/mssql/server:2019-CU15-ubuntu-20.04' 
     hostname: 'mssql' 
     #ports: 
      # - 1433:1433 
     environment: 
       - ACCEPT_EULA=Y 
       - MSSQL_SA_PASSWORD=paruexam123! 
       - MSSQL_PID=Express 
       - attach_dbs=[{'dbName':'FernGully', 'dbFiles':['/data/FernGullyExam.mdf','/data/FernGullyExam_log.ldf']}] 
     volumes: 
       - ./data:/data 
       - ./attach.sh:/attach.sh 
       - ./attach.sql:/attach.sql 
     #command: 
       #- /attach.sh 
   sqlpad: 
     # To use Dockerfile at root of this project, use build instead of image 
     # build: ../../ 
     image: sqlpad/sqlpad:5 
     hostname: 'sqlpad' 
     ports: 
       - '80:3000' 
     environment: 
       SQLPAD_ADMIN: 'admin@health.qld.gov.au' 
       SQLPAD_ADMIN_PASSWORD: 'peteisgreat' 
       SQLPAD_APP_LOG_LEVEL: info 
       SQLPAD_WEB_LOG_LEVEL: warn 
       SQLPAD_CONNECTIONS__sqlserverdemo__name: SQL Server 
       SQLPAD_CONNECTIONS__sqlserverdemo__driver: sqlserver 
       SQLPAD_CONNECTIONS__sqlserverdemo__host: mssql 
       SQLPAD_CONNECTIONS__sqlserverdemo__database: FernGully 
       SQLPAD_CONNECTIONS__sqlserverdemo__username: sa 
       SQLPAD_CONNECTIONS__sqlserverdemo__password: paruexam123! 
     volumes: 
       - sqlpad-volume:/var/lib/sqlpad 
 
volumes: 
   sqlpad-volume:
